@startuml
start

:Before BATCH DELETE;

if (primary key value is null) then(true)
    :<color:red>QueryException
    <color:red>Can't delete row
    <color:red>without primary key;
    end
else (false)
endif

:After BATCH DELETE;

if (primary key is\nmutable and optional) then(true)
    :<color:darkorange>Set primary key value to null;
else (false)
endif

stop
@enduml
