package com.urosjarc.dbmessiah.impl.db2

import com.urosjarc.dbmessiah.Schema
import com.urosjarc.dbmessiah.Serializer
import com.urosjarc.dbmessiah.data.Query
import com.urosjarc.dbmessiah.data.TypeSerializer
import kotlin.reflect.KClass


public open class Db2Serializer(
    schemas: List<Db2Schema> = listOf(),
    globalSerializers: List<TypeSerializer<*>> = listOf(),
    globalInputs: List<KClass<*>> = listOf(),
    globalOutputs: List<KClass<*>> = listOf(),
    globalProcedures: List<KClass<*>> = listOf()
) : Serializer(
    schemas = schemas,
    globalSerializers = globalSerializers,
    globalInputs = globalInputs,
    globalOutputs = globalOutputs,
    globalProcedures = globalProcedures
) {
    override val selectLastId: String = "VALUES IDENTITY_VAL_LOCAL()"

    override fun <T : Any> createTable(table: KClass<T>): Query {
        val T = this.mapper.getTableInfo(kclass = table)

        val col = mutableListOf<String>()
        val constraints = mutableListOf<String>()

        //Primary key
        val autoIncrement = if (T.primaryKey.autoInc) " GENERATED BY DEFAULT AS IDENTITY" else ""
        col.add("${T.primaryKey.name} ${T.primaryKey.dbType} PRIMARY KEY${autoIncrement}")

        //Foreign keys
        T.foreignKeys.forEach {
            val notNull = if (it.notNull) " NOT NULL" else ""
            val unique = if (it.unique) " UNIQUE" else ""
            val deleteCascade = if (it.cascadeDelete) " ON DELETE CASCADE" else ""
            val updateCascade = if (it.cascadeUpdate) " ON UPDATE CASCADE" else ""
            col.add("${it.name} ${it.dbType}$notNull$unique")
            constraints.add(
                "FOREIGN KEY (${it.name}) REFERENCES ${it.foreignTable.path} (${it.foreignTable.primaryKey.name})$updateCascade$deleteCascade"
            )
        }

        //Other columns
        T.otherColumns.forEach {
            val notNull = if (it.notNull) " NOT NULL" else ""
            val unique = if (it.unique) " UNIQUE" else ""
            col.add("${it.name} ${it.dbType}$notNull$unique")
        }

        //Connect all column definitions to one string
        val columns = (col + constraints).joinToString(", ")

        //Return created query
        return Query(sql = "CREATE TABLE IF NOT EXISTS ${T.path} ($columns)")
    }

    override fun insertRow(row: Any, batch: Boolean): Query {
        val T = this.mapper.getTableInfo(obj = row)
        return Query(
            sql = "INSERT INTO ${T.path} (${T.sqlInsertColumns()}) VALUES (${T.sqlInsertQuestions()})",
            *T.queryValues(obj = row),
        )
    }


    override fun <T : Any> dropProcedure(procedure: KClass<T>): Query {
        val P = this.mapper.getProcedure(kclass = procedure)
        var args = P.args.map { it.dbType }.joinToString(", ")
        if(P.args.isNotEmpty()) args = "($args)"
        return Query(sql = "DROP PROCEDURE ${P.path}$args")
    }

    /**
     * Generates SQL string for calling stored procedure.
     *
     * @param obj The input object representing the stored procedure to be called.
     * @return A [Query] object representing the SQL query.
     * @throws SerializerException if the [Procedure] for the object cannot be found.
     */
    public override fun <T : Any> createProcedure(procedure: KClass<T>, body: () -> String): Query {
        val P = this.mapper.getProcedure(kclass = procedure)
        val args = P.args.map { "${it.name} ${it.dbType}" }.joinToString(", ")
        return Query(
            sql = """
                CREATE OR REPLACE PROCEDURE ${P.path}($args)
                BEGIN
                    ${body()}
                END
            """.trimIndent()
        )
    }

    public override fun <T : Any> callProcedure(procedure: T): Query {
        val P = this.mapper.getProcedure(obj = procedure)

        return Query(
            sql = "CALL ${P.path}(${P.sqlArguments()})",
            *P.queryValues(obj = procedure)
        )
    }

    /**
     * Creates a new database schema if it does not already exist.
     *
     * @param schema The [Schema] object representing the schema to be created.
     * @return A [Query] object representing the SQL query to create the schema.
     */
    override fun createSchema(schema: Schema): Query {
        return Query(
            sql = """
                IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = '${schema.name}')
                BEGIN
                    EXEC( 'CREATE SCHEMA ${schema.name}' );
                END
            """
        )
    }
}
