@startuml
start
:Before BATCH INSERT;
if (primary key is auto generated in DB) then(false)

    if(primary key value is null) then(true)
        :<color:red>QueryException
        <color:red>User forgot to define primary key!;
        end
    else (false)
    endif

:INSERT with primary column value;

(true) elseif(primary key value is null) then(false)
    :<color:red>QueryException
    <color:red>Row can't be inserted again!;
    end
else (true)
    :INSERT without primary column value;
endif

stop
@enduml
