@startuml
start

:Before BATCH DELETE;

if (primary key value is null) then(false)
    :<color:red>QueryException;
    end
else (true)
endif

:After BATCH DELETE;

if (primary key is marked with ?) then(true)
    :<color:darkorange>Set primary key value to null;
else (false)
endif

stop
@enduml
