@startuml
start
:Before ROW[S] DELETE;

if (primary key value is null) then(true)
    :<color:red>QueryException
    <color:red>Can't delete row
    <color:red>without primary key;
    end
else (false)
endif

:After ROW[S] DELETE;

if (primary key is marked with ?) then(true)
    :<color:darkorange>Set primary key value to null;
else (false)
endif

stop
@enduml
