package com.urosjarc.dbmessiah.data

import com.urosjarc.dbmessiah.extend.*
import java.sql.JDBCType
import kotlin.reflect.KProperty1

/**
 * Represents [PrimaryColumn] in a [TableInfo].
 */
public class PrimaryColumn(
    kprop: KProperty1<Any, Any?>,
    dbType: String,
    jdbcType: JDBCType,
    encoder: Encoder<*>,
    decoder: Decoder<*>
) : Column(
    kprop = kprop,
    dbType = dbType,
    jdbcType = jdbcType,
    encoder = encoder,
    decoder = decoder
) {

    /**
     * Represents a boolean value indicating whether the given variable is a whole number.
     * The value of this variable is determined by the logical OR operation
     * between two properties: `kprop.ext_isWholeNumber` and `kprop.ext_isInlineWholeNumber`.
     *
     * @property isWholeNumber The boolean value indicating whether the given variable is a whole number.
     *
     * @see Column
     */
    public val isWholeNumber: Boolean = kprop.ext_isWholeNumber || kprop.ext_isInlineWholeNumber

    /**
     * Represents a boolean value indicating whether the given variable is a UUID.
     * The value of this variable is determined by the logical OR operation between two properties: `kprop.ext_isUUID` and `kprop.ext_isInlineUUID`.
     *
     * @property isUUID The boolean value indicating whether the given variable is a UUID.
     *
     * @see Column
     */
    public val isUUID: Boolean = kprop.ext_isUUID || kprop.ext_isInlineUUID

    /**
     * Represents whether a column is auto-increment.
     */
    public val autoInc: Boolean = kprop.ext_isAutoInc

    /**
     * Represents whether a column should generate an auto-generated UUID value.
     */
    public val autoUUID: Boolean = kprop.ext_isAutoUUID

    /**
     * Represents whether a column is auto-generated from the database.
     * A column can be auto-generated if it is either auto-increment or auto-generated UUID.
     */
    public val autoGenerated: Boolean = this.autoInc || this.autoUUID
}
