package com.urosjarc.dbmessiah.impl

import com.urosjarc.dbmessiah.Engine
import com.urosjarc.dbmessiah.Serializer
import com.urosjarc.dbmessiah.Service
import com.urosjarc.dbmessiah.domain.queries.Page
import com.urosjarc.dbmessiah.domain.queries.QueryBuilder
import kotlin.reflect.KClass

open class DbMessiahService(
    override val eng: Engine,
    override val ser: Serializer,
) : Service {
    override fun <T : Any> drop(kclass: KClass<T>): Int {
        val query = this.ser.dropQuery(kclass = kclass)
        val pQuery = this.eng.prepareQuery(query = query)
        return this.eng.executeUpdate(pQuery = pQuery)
    }

    override fun <T : Any> create(kclass: KClass<T>): Int {
        val query = this.ser.createQuery(kclass = kclass)
        val pQuery = this.eng.prepareQuery(query = query)
        return this.eng.executeUpdate(pQuery = pQuery)
    }

    override fun <T : Any> select(kclass: KClass<T>): List<T> {
        val query = this.ser.selectAllQuery(kclass = kclass)
        val pQuery = this.eng.prepareQuery(query = query)
        return this.eng.executeQuery(pQuery = pQuery) {
            this.ser.mapper.decode(kclass = kclass, resultSet = it)
        }
    }

    override fun <T : Any> selectPage(kclass: KClass<T>, page: Page<T>): List<T> {
        val query = this.ser.selectPageQuery(kclass = kclass, page = page)
        val pQuery = this.eng.prepareQuery(query = query)
        return this.eng.executeQuery(pQuery = pQuery) {
            this.ser.mapper.decode(kclass = kclass, resultSet = it)
        }
    }

    override fun <T : Any> insert(obj: T): Boolean {
        val T = this.ser.mapper.getTableInfo(obj = obj)
        val query = this.ser.insertQuery(obj = obj)
        val pQuery = this.eng.prepareQuery(query = query, autoGeneratedKey = T.primaryKey.kprop)
        val id = this.eng.executeInsert(pQuery = pQuery) { rs, i -> rs.getInt(i) }
        T.primaryKey.setValue(obj = obj, value = id)
        return true
    }

    override fun <T : Any> update(obj: T): Boolean {
        val query = this.ser.updateQuery(obj = obj)
        val pQuery = this.eng.prepareQuery(query = query)
        return this.eng.executeUpdate(pQuery = pQuery) == 1
    }

    fun <T : Any> delete(obj: T): Boolean {
        val query = this.ser.deleteQuery(obj = obj)
        val pQuery = this.eng.prepareQuery(query = query)
        return this.eng.executeUpdate(pQuery = pQuery) == 1
    }

    override fun <T : Any> query(kclass: KClass<T>, getSql: (queryBuilder: QueryBuilder<T>) -> String): List<T> {
//        val query = this.ser.query(sourceObj = obj, getSql = getSql)
//        val pQuery = this.eng.prepareQuery(query = query)
//        return this.eng.executeQuery(pQuery = pQuery) {
//            this.ser.mapper.decode(resultSet = it, kclass = obj::class as KClass)
//        }
        return listOf()
    }
}
