package com.urosjarc.dbmessiah

import com.urosjarc.dbmessiah.domain.queries.PreparedQuery
import com.urosjarc.dbmessiah.domain.queries.Query
import java.sql.ResultSet
import kotlin.reflect.KProperty1

interface Engine {
    fun prepareQuery(query: Query, autoGeneratedKey: KProperty1<out Any, Any?>? = null): PreparedQuery
    fun <T> executeQuery(pQuery: PreparedQuery, decodeResultSet: (rs: ResultSet) -> T): List<T>
    fun executeUpdate(pQuery: PreparedQuery): Int
    fun <T> executeInsert(pQuery: PreparedQuery, onGeneratedKeysFail: String? = null, decodeIdResultSet: ((rs: ResultSet, i: Int) -> T)): T?
    fun executeQueries(pQuery: PreparedQuery, decodeResultSet: (i: Int, rs: ResultSet) -> Unit)
}
