package com.urosjarc.dbmessiah

import com.urosjarc.dbmessiah.domain.queries.PreparedQuery
import com.urosjarc.dbmessiah.domain.queries.Query
import java.sql.ResultSet
import java.sql.Statement

interface Engine {
    fun prepareQuery(query: Query, autoGeneratedKeys: Int = Statement.NO_GENERATED_KEYS): PreparedQuery
    fun <T> executeQuery(pQuery: PreparedQuery, decodeResultSet: (rs: ResultSet) -> T): List<T>
    fun executeUpdate(pQuery: PreparedQuery): Int
    fun <T> executeInsert(pQuery: PreparedQuery, decodeIdResultSet: ((rs: ResultSet, i: Int) -> T)): List<T>
    fun executeQueries(pQuery: PreparedQuery, decodeResultSet: (i: Int, rs: ResultSet) -> Unit)
}
